# Generated by Django 4.1 on 2022-08-14 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSession',
            new_name='CourseSessionModel',
        ),
        migrations.RenameModel(
            old_name='CourseSection',
            new_name='CourseSectionModel',
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='img/courses')),
                ('update_date', models.DateTimeField()),
                ('students', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='courceregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.coursemodel'),
        ),
        migrations.AlterField(
            model_name='coursesectionmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemodel'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
