# Generated by Django 4.1 on 2022-08-14 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_rename_coursesession_coursesessionmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseModel',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='CourseSectionModel',
            new_name='CourseSection',
        ),
        migrations.RenameModel(
            old_name='CourseSessionModel',
            new_name='CourseSession',
        ),
    ]
